"""initial migration

Revision ID: 183465f5d7df
Revises: 
Create Date: 2017-12-17 08:46:48.367973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183465f5d7df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('question', sa.Integer(), nullable=False),
    sa.Column('answer_paper', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['answer_paper'], ['answer_papers.id'], ),
    sa.ForeignKeyConstraint(['question'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question', 'answer_paper')
    )
    op.drop_table('registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('answer_paper_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_paper_id'], [u'answer_papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], [u'questions.id'], )
    )
    op.drop_table('answer')
    # ### end Alembic commands ###
