"""initial migration

Revision ID: 723c4841cebf
Revises: 9cb503193663
Create Date: 2017-12-15 23:47:46.094617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723c4841cebf'
down_revision = '9cb503193663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_papers')
    op.drop_constraint(None, 'answer_papers', type_='foreignkey')
    op.drop_column('answer_papers', 'exam_paper_id')
    op.add_column('registrations', sa.Column('answer_paper_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'answer_papers', ['answer_paper_id'], ['id'])
    op.drop_column('registrations', 'exam_paper_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('exam_paper_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'exam_papers', ['exam_paper_id'], ['id'])
    op.drop_column('registrations', 'answer_paper_id')
    op.add_column('answer_papers', sa.Column('exam_paper_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'answer_papers', 'exam_papers', ['exam_paper_id'], ['id'])
    op.create_table('exam_papers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_type', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
