"""initial migration

Revision ID: 9cb503193663
Revises: f61746a2d8e9
Create Date: 2017-12-14 21:09:25.595598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb503193663'
down_revision = 'f61746a2d8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('expose_times', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('right_times', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('wrong_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'wrong_times')
    op.drop_column('questions', 'right_times')
    op.drop_column('questions', 'image')
    op.drop_column('questions', 'expose_times')
    # ### end Alembic commands ###
